@echo off
echo Starting Authentication & Security Quiz App...
echo Opening in your default browser...
start "" "index.html"
echo.
echo Quiz app should now be open in your browser!
echo Press any key to close this window...
pause >nul
